### PR TITLE
Update badges to use shields

### LINKED ISSUE #17: docs: fix badges at README.rst
- follow style from cookiecutter-invenio-module
- check settings in docs/conf.py

### PR DESCRIPTION
**Pull request by ethanhs**
Addresses #17 

Let me know if you want any tweaks to the order etc.

### CODE REVIEW

**Comment by jirikuncar** [comment]
@ethanhs the `README.rst` looks good. The idea behind #17 was to also update `docs/index.rst` and `docs/conf.py` (`setup.py` for `Sphinx` version) according to our latest Cookiecutter template so we can fully close it. Otherwise, I can just squash merge and amend the commit messages to follow our organization style and use `(addresses #17)` instead of `Resolves`.

--
- https://raw.githubusercontent.com/inveniosoftware/cookiecutter-invenio-module/master/%7B%7B%20cookiecutter.project_shortname%20%7D%7D/docs/index.rst
- https://raw.githubusercontent.com/inveniosoftware/cookiecutter-invenio-module/master/%7B%7B%20cookiecutter.project_shortname%20%7D%7D/docs/conf.py
- https://raw.githubusercontent.com/inveniosoftware/cookiecutter-invenio-module/master/%7B%7B%20cookiecutter.project_shortname%20%7D%7D/setup.py

**Comment by ethanhs** [comment]
Ah, I see. I'll close this PR and open a new one that resolves #17 as you desire.

**Comment by jirikuncar** [comment]
@ethanhs you can force push to the same branch. There is no need in closing the PR.

--
Check https://guides.github.com/introduction/flow/

**Comment by ethanhs** [comment]
@jirikuncar Go ahead and squash merge and I've changed resolves to addresses.

**Comment by lnielsen** [comment]
LGTM

**Pull request closed without merging**
