### PR TITLE
datacite-schema: 3.1 and 4.0 titleType fix

### PR DESCRIPTION
**Pull request by krzysztof**
* Keeps the "type" for backwards-compatibility

Co-authored-by: Thomas Morrell
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

### CODE REVIEW

**Comment by krzysztof** [comment]
@lnielsen should unit test make a connection to an online service?

**Comment by lnielsen** [comment]
No, all tests should be mocked. Grep for ``httpretty``.

**Comment by lnielsen** [comment]
Could perhaps have to do with new version of ``requests`` library.

**Comment by jirikuncar** [comment]
I have been using [`responses`](https://pypi.python.org/pypi/responses) instead of `httpretty`.

**Comment by krzysztof** [comment]
@jirikuncar looks like this was a common response: https://github.com/gabrielfalcao/HTTPretty/issues/242#issuecomment-227419197

**Pull request merged**
