### PR TITLE
4.2 schema updates from DataCite

### PR DESCRIPTION
**Pull request by tmorrell**
Get the latest 4.2 schema updates from DataCite.  I'm still working on the XML<->JSON transform for identifiers.  Both identifier and alternative identifiers in the XML need to get merged into the identifiers field in JSON.  I'll also add a small description on the changes between the 4.1 schema and 4.2 DataCite schema (beyond just the new metadata fields).

### CODE REVIEW

**Comment by tmorrell** [comment]
I've gotten the identifiers transform to work correctly, but we may want to wait for https://github.com/datacite/schema/pull/68 to get merged to avoid another PR.

**Comment by lnielsen** [comment]
I would prefer we wait until the "official" 4.2 schema is fully locked down. I think there's still a couple of discussions to take like datacite/schema#68 but also the [identifiers vs alternate identifiers](https://github.com/datacite/schema/issues/52#issuecomment-482072302)

Also, can I ask you to rebase and create logical commits, otherwise it is very hard for me to review it. Here's how I would structure it:

1. a commit for changing the identifier + alternative_identifiers into identifiers (``schema42.py``, ``datacite-v4.2.json ``, ``test_schema42.py``, ``xmlutils.py``, ``conftest.py``, only the identifiers property in examples). Only change actual lines that need change (e.g. don't include JSON reformatting changes for datacite-v4.2.json and examples)
2. a commit for adding new test JSON files
3. a commit for reformatting JSON files (schema + examples)
4. a commit for CHANGES.rst

This way I can clearly see the behaviour change (bullet 1) and what impact it has on examples files without having to understand if it's just reformatting or the behaviour changed. Also, there's less risk that I miss to see important changes (changes to example files are often a good indicator to understand how the behaviour changed). It also drastically reduce the number of lines I have to carefully review, vs what I just need to skim through (e.g. I don't have to review pure reformatting much). Once the code is merged, it is also a lot easier to track down bugs and understand why something was changed when using logical commits.

Two last things, I'd also like to ask:
- For each logical commit add a descriptive commit message why something was changed
- Match commit message style to previous commit history and ensure there's no merge commits in the history.

**Comment by tmorrell** [comment]
Thanks @lnielsen! I've reorganized the commits to make more sense.  I'm not sure how I changed the spacing in the jsonschema when I did the first PR, but the first commit is just matching what is currently in datacite/schema.  The rest are the actual changes to get identifier + alternative_identifiers working correctly, an extra test (which can be removed if you don't like it), and the docs.  

No problem waiting until 4.2 is settled. I'll rebase my other PRs once this is merged.

**Comment by tmorrell** [comment]
It doesn't seem like there will be any more changes to 4.2 @lnielsen. If the formatting changes are too much I can re-do the pull request and separate out formatting from the identifiers changes, but since I'm just syncing with DataCite I think it would have to be manual.

Once 4.2 is merged I can rebase the 4.3 PR.

**Comment by tmorrell** [comment]
Oh, and in case it's not clear I'm not including the geopoints as floats component. It might make sense for a general jsonschema, but I can't figure out a straightforward way to implement it in a way that makes sense in Python.

**Comment by tmorrell** [comment]
Rebased with master so Travis passes

**Comment by tmorrell** [comment]
@lnielsen I've added a new PR https://github.com/inveniosoftware/datacite/pull/57 to address an issue with isort that was making travis fail. I've included the new PR in all my existing PRs, so start with the new one. Thanks!

**Pull request merged**
