### PR TITLE
Remove usages of mutable default arguments

### PR DESCRIPTION
**Pull request by sloria**
Default arguments are evaluated once, when methods are defined.
Multiple calls to the same method could therefore use the same
dictionary, which could lead to hard-to-trace bugs.

http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments

### CODE REVIEW

**Comment by lnielsen** [comment]
Thanks @sloria! I need to add a copyright line in the changed files - would that be you personally or Center for Open Science?

Do you need a fast release of the changes?

**Comment by sloria** [comment]
@lnielsen These changes should go under Center for Open Science.

No rush on the release of these changes.

**Comment by sloria** [comment]
Thanks for the fixups when you merged. I'll make sure to update the Copyright statements myself next time I contribute.

**Comment by lnielsen** [comment]
No worries, it's not an issue at all.

**Pull request merged**
